/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wang_walker_jnidemo_JniTest */

#ifndef _Included_com_wang_walker_jnidemo_JniTest
#define _Included_com_wang_walker_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wang_walker_jnidemo_JniTest
 * Method:    getJniText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wang_walker_jnidemo_JniTest_getJniText
  (JNIEnv *, jobject);

/*
 * Class:     com_wang_walker_jnidemo_JniTest
 * Method:    logJniText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wang_walker_jnidemo_JniTest_logJniText__
  (JNIEnv *, jobject);

/*
 * Class:     com_wang_walker_jnidemo_JniTest
 * Method:    logJniText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wang_walker_jnidemo_JniTest_logJniText__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
